using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace BasselRamiProj
{
    class ListOfAllCountries
    {
        public IList<string> list = new List<string>();
        public ListOfAllCountries()
        {
            list.Add("None");
            list.Add("Afghanistan");
            list.Add("Albania");
            list.Add("Algeria");
            list.Add("American Samoa");
            list.Add("Andorra");
            list.Add("Angola");
            list.Add("Anguilla");
            list.Add("Antarctica");
            list.Add("Antigua and Barbuda");
            list.Add("Argentina");
            list.Add("Armenia");
            list.Add("Aruba");
            list.Add("Australia");
            list.Add("Austria");
            list.Add("Azerbaijan");
            list.Add("Bahamas");
            list.Add("Bahrain");
            list.Add("Bangladesh");
            list.Add("Barbados");
            list.Add("Belarus");
            list.Add("Belgium");
            list.Add("Belize");
            list.Add("Benin");
            list.Add("Bermuda");
            list.Add("Bhutan");
            list.Add("Bolivia");
            list.Add("Bosnia and Herzegovina");
            list.Add("Botswana");
            list.Add("Brazil");
            list.Add("Brunei Darussalam");
            list.Add("Bulgaria");
            list.Add("Burkina Faso");
            list.Add("Burundi");
            list.Add("Cambodia");
            list.Add("Cameroon");
            list.Add("Canada");
            list.Add("Cape Verde");
            list.Add("Cayman Islands");
            list.Add("Central African Republic");
            list.Add("Chad");
            list.Add("Chile");
            list.Add("China");
            list.Add("Christmas Island");
            list.Add("Cocos (Keeling) Islands");
            list.Add("Colombia");
            list.Add("Comoros");
            list.Add("Democratic Republic of the Congo (Kinshasa)");
            list.Add("Congo, Republic of (Brazzaville)");
            list.Add("Cook Islands");
            list.Add("Costa Rica");
            list.Add("Ivory Coast");
            list.Add("Croatia");
            list.Add("Cuba");
            list.Add("Cyprus");
            list.Add("Czech Republic");
            list.Add("Denmark");
            list.Add("Djibouti");
            list.Add("Dominica");
            list.Add("Dominican Republic");
            list.Add("East Timor (Timor-Leste)");
            list.Add("Ecuador");
            list.Add("Egypt");
            list.Add("El Salvador");
            list.Add("Equatorial Guinea");
            list.Add("Eritrea");
            list.Add("Estonia");
            list.Add("Ethiopia");
            list.Add("Falkland Islands");
            list.Add("Faroe Islands");
            list.Add("Fiji");
            list.Add("Finland");
            list.Add("France");
            list.Add("French Guiana");
            list.Add("French Polynesia");
            list.Add("French Southern Territories");
            list.Add("Gabon");
            list.Add("Gambia");
            list.Add("Georgia");
            list.Add("Germany");
            list.Add("Ghana");
            list.Add("Gibraltar");
            list.Add("Great Britain");
            list.Add("Greece");
            list.Add("Greenland");
            list.Add("Grenada");
            list.Add("Guadeloupe");
            list.Add("Guam");
            list.Add("Guatemala");
            list.Add("Guinea");
            list.Add("Guinea-Bissau");
            list.Add("Guyana");
            list.Add("Haiti");
            list.Add("Holy See");
            list.Add("Honduras");
            list.Add("Hong Kong");
            list.Add("Hungary");
            list.Add("Iceland");
            list.Add("India");
            list.Add("Indonesia");
            list.Add("Iran (Islamic Republic of)");
            list.Add("Iraq");
            list.Add("Ireland");
            list.Add("Israel");
            list.Add("Italy");
            list.Add("Jamaica");
            list.Add("Japan");
            list.Add("Jordan");
            list.Add("Kazakhstan");
            list.Add("Kenya");
            list.Add("Kiribati");
            list.Add("Korea, Democratic People's Rep. (North Korea)");
            list.Add("Korea, Republic of (South Korea)");
            list.Add("Kosovo");
            list.Add("");
            list.Add("Kuwait");
            list.Add("Kyrgyzstan");
            list.Add("Lao, People's Democratic Republic");
            list.Add("Latvia");
            list.Add("Lebanon");
            list.Add("Lesotho");
            list.Add("Liberia");
            list.Add("Libya");
            list.Add("Liechtenstein");
            list.Add("Lithuania");
            list.Add("Luxembourg");
            list.Add("Macau");
            list.Add("Macedonia, Rep. of");
            list.Add("Madagascar");
            list.Add("Malawi");
            list.Add("Malaysia");
            list.Add("Maldives");
            list.Add("Mali");
            list.Add("Malta");
            list.Add("Marshall Islands");
            list.Add("Martinique");
            list.Add("Mauritania");
            list.Add("Mauritius");
            list.Add("Mayotte");
            list.Add("Mexico");
            list.Add("Micronesia, Federal States of");
            list.Add("Moldova, Republic of");
            list.Add("Monaco");
            list.Add("Mongolia");
            list.Add("Montenegro");
            list.Add("Montserrat");
            list.Add("Morocco");
            list.Add("Mozambique");
            list.Add("Myanmar, Burma");
            list.Add("Namibia");
            list.Add("Nauru");
            list.Add("Nepal");
            list.Add("Netherlands");
            list.Add("Netherlands Antilles");
            list.Add("New Caledonia");
            list.Add("New Zealand");
            list.Add("Nicaragua");
            list.Add("Niger");
            list.Add("Nigeria");
            list.Add("Niue");
            list.Add("Northern Mariana Islands");
            list.Add("Norway");
            list.Add("Oman");
            list.Add("Pakistan");
            list.Add("Palau");
            list.Add("Palestinian territories");
            list.Add("Panama");
            list.Add("Papua New Guinea");
            list.Add("Paraguay");
            list.Add("Peru");
            list.Add("Philippines");
            list.Add("Pitcairn Island");
            list.Add("Poland");
            list.Add("Portugal");
            list.Add("Puerto Rico");
            list.Add("Qatar");
            list.Add("Reunion Island");
            list.Add("Romania");
            list.Add("Russian Federation");
            list.Add("Rwanda");
            list.Add("Saint Kitts and Nevis");
            list.Add("Saint Lucia");
            list.Add("Saint Vincent and the Grenadines");
            list.Add("Samoa");
            list.Add("San Marino");
            list.Add("Sao Tome and Principe");
            list.Add("Saudi Arabia");
            list.Add("Senegal");
            list.Add("Serbia");
            list.Add("Seychelles");
            list.Add("Sierra Leone");
            list.Add("Singapore");
            list.Add("Slovakia (Slovak Republic)");
            list.Add("Slovenia");
            list.Add("Solomon Islands");
            list.Add("Somalia");
            list.Add("South Africa");
            list.Add("South Sudan");
            list.Add("Spain");
            list.Add("Sri Lanka");
            list.Add("Sudan");
            list.Add("Suriname");
            list.Add("Swaziland");
            list.Add("Sweden");
            list.Add("Switzerland");
            list.Add("Syria, Syrian Arab Republic");
            list.Add("Taiwan (Republic of China)");
            list.Add("Tajikistan");
            list.Add("Tanzania; officially the United Republic of Tanzania");
            list.Add("Thailand");
            list.Add("Tibet");
            list.Add("Timor-Leste (East Timor)");
            list.Add("Togo");
            list.Add("Tokelau");
            list.Add("Tonga");
            list.Add("Trinidad and Tobago");
            list.Add("Tunisia");
            list.Add("Turkey");
            list.Add("Turkmenistan");
            list.Add("Turks and Caicos Islands");
            list.Add("Tuvalu");
            list.Add("Uganda");
            list.Add("Ukraine");
            list.Add("United Arab Emirates");
            list.Add("United Kingdom");
            list.Add("United States");
            list.Add("Uruguay");
            list.Add("Uzbekistan");
            list.Add("Vanuatu");
            list.Add("Vatican City State (Holy See)");
            list.Add("Venezuela");
            list.Add("Vietnam");
            list.Add("Virgin Islands (British)");
            list.Add("Virgin Islands (U.S.)");
            list.Add("Wallis and Futuna Islands");
            list.Add("Western Sahara");
            list.Add("Yemen");
            list.Add("Zambia");
            list.Add("Zimbabwe");


        }
    }
}
